apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dacha.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels: {{ include "dacha.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
