apiVersion: v2
name: dacha-chart
description: Dacha - SNT website with embedded frontend and Go backend
type: application
version: 0.1.0
appVersion: "1.0.0"
home: https://git.k8s.crashpoint.ru/xver1xrd/dacha
sources:
  - https://git.k8s.crashpoint.ru/xver1xrd/dacha
maintainers:
  - name: xver1xrd