replicaCount: 2

image:
  backendRepository: harbor.k8s.crashpoint.ru/xver1xrd/dacha-backend
  frontendRepository: harbor.k8s.crashpoint.ru/xver1xrd/dacha-frontend
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-pull-secret

backend:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi

frontend:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

pvc:
  storage: 1Gi
  storageClassName: local-path

ingress:
  frontendHost: dacha.k8s.crashpoint.ru
  clusterIssuer: letsencrypt-prod
  className: nginx
